### ISSUE TITLE
HTML Snippets May Break / Get Cut-Off Before Closing Tag (was: Strange handling of code blocks)

### ISSUE THREAD

**Issue by infominer33** [planet-templates/planet-blank#5] opened 2020-05-24 16:06 UTC
I've been trying to figure this out for a while, even just to understand what is actually happening.

I'm not sure that this is a problem with this theme, but it only presents on blank.. 

Basically, after a post containing a codeblock, the rest of the page is wrapped in a codeblock, leaving the rest of the page in `font-family: monospace;` thus not printing full-sized headers.

![image](https://user-images.githubusercontent.com/44134283/82758711-29da4300-9db6-11ea-869e-d75871e4a57f.png)

![image](https://user-images.githubusercontent.com/44134283/82758828-e9c79000-9db6-11ea-8395-1bf5fc6646fd.png)

**Comment by geraldb** [comment] 2020-05-24 17:22
I'd say the error is in the textify helper <https://github.com/planet-templates/planet-blank/blob/master/blank.html.erb#L128>, see as an example, that tries to sanitize (clean-up) the html content from the feed item / article.   The html whitelist and source is here<https://github.com/textkit/textutils/blob/master/textutils/lib/textutils/helper/hypertext_helper.rb#L96>.

To help debug / find the error can you post the "original" (static) html source of the generated page (using the brower show source menu) or do you have link?  - if you use the (live / dynamic) DOM tree as in your example  than you get the browser fixed-up version - and sorry I can't tell where the missing closing tag is.

**Comment by geraldb** [comment] 2020-05-24 17:30
Update:  Looks like the snippet is the cause - it just cuts-off the snippet after 400 chars (thus, cutting off closing tags) - it's supposed to get converted to text / markdown but isn't yet.  For a quick workaround try / change:

```
<div class='item-snippet'>
<!-- use 'smarter' algorithm for cutoff snippet text
   note: summary goes first; than try content -->
<% if item.summary %>
  <%= textify( item.summary )[0..400] %>
<% elsif item.content %>
  <%= textify( item.content )[0..400] %>
<% else %>
  -/-
<% end %>
</div>
```

To:

```
<div class='item-snippet'>
<% if item.summary %>
  <%= whitelist( item.summary, [] )[0..400] %>
<% elsif item.content %>
  <%= whitelist( item.content, [] )[0..400] %>
<% else %>
  -/-
<% end %>
</div>
```
That should remove all html tags for sure (empty tag list []).

**Comment by infominer33** [comment] 2020-05-24 17:33
!!! brilliant! I did not realize that the original source would be different than what's shown in the console!

I was just about to paste the offending snippet section, but you beat me to the punch!

thanks again! Love pluto and all it's helpers!

**Comment by geraldb** [comment] 2020-05-24 17:35
Thanks for your kind words and patience.  Sorry the html to text (markdown) conversion for snippets was planned but unfortunately isn't there yet (and, thus, the current snippet generation is somewhat broken).

**Closed as completed** 2020-05-24 17:47 UTC
Labels: bug
